### ISSUE TITLE
Problem with Permissions on /dev/bpf* on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by vikaskyadav** [kylemcdonald/FreeWifi#7] opened 2017-02-04 18:38 UTC
sudo chmod o+r /dev/bpf* not working. Infact dev doesn't contain any bpf* named directory or file.

**Comment by kylemcdonald** [comment] 2017-02-04 20:48
Duplicate of #3

**Closed by kylemcdonald** 2017-02-04 20:48 UTC
